// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzwobeiltxqawibcwhgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6d29iZWlsdHhxYXdpYmN3aGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4NjM3NjAsImV4cCI6MjA4NTQzOTc2MH0.6zcyf6mC9-LwAogYTNxRfHgulK4v3JRJIUpNOBk72ok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});